name: Deploy Documentation

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: "20.10.0"

      - name: Install modules
        run: npm i

      - name: Deploy to gh-pages branch
        env:
          TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          WORKSPACE_DIR: "${{ github.workspace }}"
          GITHUB_SHA: "${{ github.sha }}"
        run: npm run deploy-gh-pages
